---
# tasks file for gotify
- name: Ensure Gotify directories and files are there
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode }}"
  loop:
    # Andere Verzeichnisse und Dateien...
    - {
        path: "{{ docker_config_path }}/gotify",
        state: directory,
        mode: "0755",
      }
